apiVersion: 'vlabs'
location: <azure-region>
name: <aks-cluster-name>
properties:
  kubernetesVersion: <kubernetes-version>
  dnsPrefix: <dns-prefix>
  agentPoolProfiles:
  - name: <agent-pool-name>
    count: <node-count>
    vmSize: <node-vm-size>
    osDiskSizeGB: <os-disk-size>
  linuxProfile:
    adminUsername: <admin-username>
    ssh:
      publicKeys:
      - keyData: <ssh-public-key>
  servicePrincipalProfile:
    clientId: <client-id>
    secret: <client-secret>
  networkProfile:
    networkPlugin: <network-plugin>
    dnsServiceIp: <dns-service-ip>
    serviceCidr: <service-cidr>
    dockerBridgeCidr: <docker-bridge-cidr>
