name: Create AKS Cluster
on:
  push:
    branches:
      - main

jobs:
  create-aks-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create AKS Cluster
        run: |
          az aks create \
            --resource-group <resource-group-name> \
            --name <aks-cluster-name> \
            --node-count <node-count> \
            --node-vm-size <node-vm-size> \
            --location <azure-region> \
            --generate-ssh-keys
