name: Build the images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Generate Private Key
        run: |
           ${{ secrets.PRIVATE_KEY }}=$(openssl genrsa 2048)
 
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          
      - name: Push the image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }} .
          ${{ secrets.DOCKER_KEY }}=$(docker trust key generate)
          docker trust sign --local ${{ secrets.DOCKER_KEY }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}
          docker push  ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}
 
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref:  ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}
 
          
     
         

        
